name: Update DAppNode package

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '* * * * *'
jobs:
  dappnodepackage-update:
    name: Trigger the DAppNode Package update
    runs-on: ubuntu-latest
    env: 
      DISPATCH_REPO: dappnode/DAppNodePackage-lighthouse-medalla-beacon-chain
      UPSTREAM_REPO: sigp/lighthouse
    steps:
    - uses: actions/checkout@v2
    - name: Get the tag
      id: get_tag
      run: |
        UPSTREAM_TAG=$(curl https://api.github.com/repos/$UPSTREAM_REPO/tags | jq .[0].name | tr -d "\"" )
        DNP_UPSTREAM=$(cat dappnode_package.json | jq .upstreamVersion | tr -d "\"" )
        if [ $UPSTREAM_TAG != $DNP_UPSTREAM ];then
            echo "::set-output name=trigger_update::true"
        fi
        echo ::set-output name=TAG::$UPSTREAM_TAG

    - name: update UPSTREAM_VERSION
      run: |
        sed -i "s/        UPSTREAM_VERSION: .*/        UPSTREAM_VERSION: ${{ steps.get_tag.outputs.TAG }}/g" docker-compose.yml

    - name: Commit changes
      run: |
          git config --global user.email "eduadiez@gmail.com"
          git config --global user.name "Eduardo"
          git commit -am "Github action bumped version to ${{ steps.get_tag.outputs.TAG }}"
          git push